version: '3.8'

services:
  backend:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - static_data:/app/staticfiles
    depends_on:
      - redis
    networks:
      - tradeleague

  nginx:
    image: nginx:1.25-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_data:/app/staticfiles:ro
    depends_on:
      - backend
    networks:
      - tradeleague

  redis:
    image: redis:7-alpine
    restart: always
    networks:
      - tradeleague

volumes:
  static_data:

networks:
  tradeleague:
    driver: bridge
