version: '3.8'

services:                                                                                                           
    backend:                                                                                                          
      build: .                                                                                                        
      volumes:                                                                                                        
        - .:/app                                                                                                      
      ports:                                                                                                          
        - "8000:8000"                                                                                                 
      environment:                                                                                                    
        - DEBUG=True                                                                                                  
        - ALLOWED_HOSTS=localhost,127.0.0.1,backend 