# Generated by Django 6.0.2 on 2026-02-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="account_balance",
            field=models.FloatField(default=100000),
        ),
    ]
