# Generated by Django 5.0.14 on 2026-01-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="account_balance",
            field=models.FloatField(default=100000),
        ),
    ]
