# Generated by Django 5.0.14 on 2026-01-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_profile_account_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="account_balance",
            field=models.FloatField(default=0),
        ),
    ]
